### ISSUE TITLE
MacOS: Invalid context, try updating your config or switching context

### ISSUE THREAD

**Issue by luvpreetsingh** [rekon-oss/portfall#9]
### Description

I installed portfall and launched it but I keep getting 

```
Invalid context, try updating your config or switching context
```

When I go to settings(at the right bottom), I update the context to a different cluster. The config gets updated but still it doesn't work.

Is there anything you can help me with to debug this?

**Comment by Rested** [comment]
Hi @luvpreetsingh thanks for trying Portfall! Is it the context you are changing or the config file? And can you connect normally using `kubectl`? If so what is the k8s provider (e.g kind, k3d, aks, gke, etc) and authentication method.

**Comment by luvpreetsingh** [comment]
@Rested it is the context I am trying to change.

I can connect normally using kubectl, no issues there.

I am using AWS EKS, v1.15.

Authentication method is by AWS IAM.

**Comment by Rested** [comment]
Hey @luvpreetsingh I've pushed a new version which has a little debug icon at the bottom. If you could download that and post the logs here from clicking the debug icon. Then I should be able to help better :)

**Comment by luvpreetsingh** [comment]
```
[WARN]: [Client] Found no namespaces
[DEBUG]:
[WARN]: [Client] Failed to get pods in ns default
[WARN]: [Client] Found no namespaces
````

This is the output in the debug console

**Comment by Rested** [comment]
That's weird - the answer should be in that debug message but for some reason it's not showing up. Can you try running it from terminal and pasting the output of that?

**Comment by jorgex1** [comment]
Hi @Rested im seeing the samething (running in debian + kubectl works just fine + same exact output from the debug console).
How would run run portfall from the console?

Also, any chance that the error may be due to the use of the aws-iam-authenticator?
A lot of people that run kubernetes in aws, and EKS by default, use that component to manage authentication. It does however require the client (e.g., kubectl) to generate a token to be used for a request.

**Comment by luvpreetsingh** [comment]
Sorry @Rested, didn't get time to try it out. will try.

I tried lens and it worked perfectly fine, https://github.com/lensapp/lens
